import { useEffect, useState } from 'react';
import { Sparkles, Pencil, X, Check } from 'lucide-react';
import RichTextEditor from '../RichTextEditor';
import RichTextViewer from '../RichTextViewer';
import { useToast } from '../../contexts/ToastContext';
import { generateNotesSummary, updateNotesSummary } from '../../api/notes';
import { fetchJiraConfig } from '../../api/jira';
import styles from './NotesSummaryPanel.module.css';

const formatTime = (isoString) => {
  return new Intl.DateTimeFormat('en-AU', {
    year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
  }).format(new Date(isoString));
};

const NotesSummaryPanel = ({ featureId, initialSummary = null, notesCount = 0, newestNoteCreatedAt = null }) => {
  const { addToast } = useToast();
  const [summary, setSummary] = useState(initialSummary);
  const [summarising, setSummarising] = useState(false);
  const [aiConfigured, setAiConfigured] = useState(false);
  const [isEditingSummary, setIsEditingSummary] = useState(false);
  const [summaryEditDraft, setSummaryEditDraft] = useState('');
  const [savingSummary, setSavingSummary] = useState(false);

  useEffect(() => {
    setSummary(initialSummary);
    setIsEditingSummary(false);
    setSummaryEditDraft('');
  }, [featureId, initialSummary]);

  useEffect(() => {
    let cancelled = false;
    fetchJiraConfig()
      .then((cfg) => { if (!cancelled) setAiConfigured(!!cfg.aiConfigured); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, []);

  const isStale = summary && newestNoteCreatedAt && new Date(newestNoteCreatedAt) > new Date(summary.generatedAt);

  const handleSummarise = async () => {
    setSummarising(true);
    try {
      const result = await generateNotesSummary(featureId);
      setSummary(result);
      addToast('Summary generated', 'success');
    } catch (err) {
      addToast(err.error || 'Failed to generate summary', 'error');
    } finally {
      setSummarising(false);
    }
  };

  const startEditSummary = () => {
    setIsEditingSummary(true);
    setSummaryEditDraft(summary.content);
  };

  const cancelEditSummary = () => {
    setIsEditingSummary(false);
    setSummaryEditDraft('');
  };

  const handleSaveSummary = async () => {
    if (!summaryEditDraft.trim()) return;
    setSavingSummary(true);
    try {
      const updated = await updateNotesSummary(featureId, summaryEditDraft);
      setSummary(updated);
      setIsEditingSummary(false);
      setSummaryEditDraft('');
      addToast('Summary updated', 'success');
    } catch {
      addToast('Failed to update summary', 'error');
    } finally {
      setSavingSummary(false);
    }
  };

  if (!aiConfigured) return null;

  return (
    <div className={styles.summaryPanel}>
      <div className={styles.header}>
        <span className={styles.headerLabel}>Internal Notes Summary</span>
        <span className={styles.headerBadge}>AI Generated</span>
      </div>
      {summary ? (
        <>
          <div className={styles.summaryMeta}>
            <span>Generated by {summary.generatedByName} on {formatTime(summary.generatedAt)}</span>
            {isStale && <span className={styles.staleBadge}>New notes since this summary</span>}
          </div>
          {isEditingSummary ? (
            <div className={styles.editArea}>
              <RichTextEditor value={summaryEditDraft} onChange={setSummaryEditDraft} />
              <div className={styles.editActions}>
                <button type="button" onClick={handleSaveSummary} className={styles.saveBtn} disabled={savingSummary}>
                  <Check size={13} /> {savingSummary ? 'Saving…' : 'Save'}
                </button>
                <button type="button" onClick={cancelEditSummary} className={styles.cancelBtn}>
                  <X size={13} /> Cancel
                </button>
              </div>
            </div>
          ) : (
            <RichTextViewer content={summary.content} className={styles.summaryContent} />
          )}
        </>
      ) : (
        <p className={styles.summaryEmpty}>No summary yet.</p>
      )}
      <div className={styles.summaryActions}>
        <button
          type="button"
          className={styles.summariseBtn}
          onClick={handleSummarise}
          disabled={summarising || notesCount === 0 || isEditingSummary}
          title={notesCount === 0 ? 'Add at least one note first' : undefined}
        >
          <Sparkles size={14} />
          {summarising ? 'Summarising…' : summary ? 'Regenerate summary' : 'Summarise notes'}
        </button>
        {summary && !isEditingSummary && (
          <button
            type="button"
            className={styles.summariseBtn}
            onClick={startEditSummary}
          >
            <Pencil size={14} />
            Edit summary
          </button>
        )}
      </div>
    </div>
  );
};

export default NotesSummaryPanel;
