import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import NotesSummaryPanel from './NotesSummaryPanel';
import * as notesApi from '../../api/notes';
import * as jiraApi from '../../api/jira';

vi.mock('../../api/notes');
vi.mock('../../api/jira');

vi.mock('../../contexts/ToastContext', () => ({
  useToast: () => ({ addToast: vi.fn() }),
}));

vi.mock('../RichTextEditor', () => ({
  default: ({ value, onChange, placeholder }) => (
    <textarea
      data-testid="rich-text-editor"
      placeholder={placeholder}
      value={value}
      onChange={(e) => onChange(e.target.value)}
    />
  ),
}));

vi.mock('../RichTextViewer', () => ({
  default: ({ content }) => <div data-testid="rich-text-viewer">{content}</div>,
  getPlainTextFromRichText: (value) => value,
}));

describe('NotesSummaryPanel', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    jiraApi.fetchJiraConfig.mockResolvedValue({ baseUrl: '', aiConfigured: true });
  });

  it('hides the panel entirely when AI is not configured', async () => {
    jiraApi.fetchJiraConfig.mockResolvedValue({ baseUrl: '', aiConfigured: false });
    const { container } = render(<NotesSummaryPanel featureId="feature-1" />);
    await waitFor(() => expect(jiraApi.fetchJiraConfig).toHaveBeenCalled());
    expect(container.firstChild).toBeNull();
  });

  it('renders initial summary correctly', async () => {
    const summary = { content: 'This is the AI summary', generatedAt: '2026-07-05T00:00:00Z', generatedByName: 'Admin User' };
    render(<NotesSummaryPanel featureId="feature-1" initialSummary={summary} />);
    await screen.findByText('This is the AI summary');
    expect(screen.getByText(/Generated by Admin User/)).toBeInTheDocument();
  });

  it('shows a stale badge when a newer note exists than the saved summary', async () => {
    const summary = { content: 'Old summary', generatedAt: '2026-06-01T00:00:00Z', generatedByName: 'Admin' };
    render(
      <NotesSummaryPanel
        featureId="feature-1"
        initialSummary={summary}
        notesCount={1}
        newestNoteCreatedAt="2026-07-01T00:00:00Z"
      />
    );
    await screen.findByText('New notes since this summary');
  });

  it('allows the summary to be edited and saved', async () => {
    const summary = { content: 'Initial summary', generatedAt: '2026-07-05T00:00:00Z', generatedByName: 'Admin' };
    notesApi.updateNotesSummary.mockResolvedValue({
      content: 'Updated summary text',
      generatedAt: '2026-07-09T00:00:00Z',
      generatedByName: 'Jane Smith',
    });

    render(<NotesSummaryPanel featureId="feature-1" initialSummary={summary} />);

    await screen.findByText('Initial summary');
    
    // Click Edit summary
    fireEvent.click(screen.getByText('Edit summary'));

    // The editor should have the initial summary value
    const summaryEditor = screen.getByTestId('rich-text-editor');
    expect(summaryEditor.value).toBe('Initial summary');

    // Change text and click save
    fireEvent.change(summaryEditor, { target: { value: 'Updated summary text' } });
    fireEvent.click(screen.getByText('Save'));

    await waitFor(() => expect(notesApi.updateNotesSummary).toHaveBeenCalledWith('feature-1', 'Updated summary text'));
    await screen.findByText('Updated summary text');
  });
});
